on:
  workflow_dispatch: # Trigger manually 
    inputs:
      tag_name:
      committish:

name: Create_Release

jobs:
  build:
    name: Create_Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          commitish: ${{ github.event.inputs.committish }}
          generateReleaseNotes: true
          release_name: Release ${{ github.event.inputs.tag_name }}
          draft: false
          prerelease: false
